name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  integration:
    runs-on: ubuntu-latest-16-cores

    env:
      MAVEN_RAVELIN_USERNAME: ${{ vars.MAVEN_RAVELIN_USERNAME }}
      MAVEN_RAVELIN_PASSWORD: ${{ secrets.MAVEN_RAVELIN_PASSWORD }}
      BT_API_KEY_PVT: ${{ secrets.BT_API_KEY_PVT }}
      BT_API_KEY_PUB: ${{ secrets.BT_API_KEY_PUB }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npx envinfo

      - uses: gradle/actions/setup-gradle@v3

      # https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
      - name: Enable KVM group perms for hardware acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup JDK version
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2.4.2

      - name: Run web server
        run: |
          make start-dev-server

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          target: default
          cores: 2
          profile: pixel_3a
          ram-size: 4096M
          sdcard-path-or-size: 100M
          force-avd-creation: false
          emulator-boot-timeout: 900 # 15min
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          pre-emulator-launch-script: |
            echo "Running pre emulator launch script. Printing the working directory now:"
            pwd
          script: make run-e2e

      - name: Generate Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: E2E Report (x86_64, x86_64, default)
          path: |
            ${{ github.workspace }}/*.mp4
            ${{ github.workspace }}/*.png
            ${{ github.workspace }}/**/emulator_logcat.txt
            ${{ github.workspace }}/report*.xml
            ~/.maestro/results /**/*

  code-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}
        with:
          command: code test

  dependencies-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}
        with:
          args: --all-sub-projects --severity-threshold=high
